<!DOCTYPE html>
<html>
<head>
  <title></title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


<style >
  /* Palette generated by Material Palette - materialpalette.com/blue-grey/cyan */
.dark-primary-color    { background: #455A64; }
.default-primary-color { background: #607D8B; }
.light-primary-color   { background: #CFD8DC; }
.text-primary-color    { color: #FFFFFF; }
.accent-color          { background: #00BCD4; }
.primary-text-color    { color: #212121; }
.secondary-text-color  { color: #757575; }
.divider-color         { border-color: #BDBDBD; }
.barra-superior{
  width: 100%;
  min-height: 15px;
}
.navbar{
  border: 0px;
  min-height: 70px;
  border-radius: 0px;
}
.navbar-default .navbar-text {
  color: white;
}
.navbar-default .navbar-nav>li>a{
  color:white;
}
.navbar-default .navbar-brand {
    color: white;
    font-size: 40px;
}
.navbar-default .navbar-toggle {
    border-color: transparent;
}
.navbar-default .navbar-toggle .icon-bar {
    background-color: white;
}
.navbar-default .navbar-toggle:focus, .navbar-default .navbar-toggle:hover {
    background-color: transparent;
}
</style>

</head>
<body>

      <!-- Static navbar -->
      <nav class="navbar navbar-default default-primary-color" >
        <div class="barra-superior dark-primary-color">
        </div>
          <div class="container-fluid">

            <div class="navbar-header">

              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" >Locator Jobs</a>



            </div>

            <!-- Fin Navegacion Movil -->

            <div id="navbar" class="navbar-collapse collapse">
          
              <ul class="nav navbar-nav ">
              <ul class="nav navbar-nav navbar-left">
              
              </ul>
              </ul>
            </div>
          </div>
        </nav>


        <div class="container">
            @if(isset($nombre))
                Hola, {{$nombre}} <br>
                <h2>Bienvenido a Locator Jobs.</h2>
                <br>
                Usted se ha registrado en Locator Jobs, pero necesitamos que active su cuenta para poder utilizarla. Puede activar su cuenta con este <a href="{{url('/usuarios/'.$email.'/activar')}}">enlace.</a>
            @else
            <h2>No perteneces aquí</h2>
            @endif
        </div>
  </body> 
  </html>